# Generated by Django 5.1.1 on 2026-05-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
    ]
