# Generated by Django 5.1.1 on 2026-10-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple_app', '0002_mediaitem_is_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visitor Log',
                'verbose_name_plural': 'Visitor Logs',
                'ordering': ['-visited_at'],
            },
        ),
    ]
